services:
  prometheus:
    image: prom/prometheus:latest
    container_name: jaus-prometheus
    networks:
      - jaus_network
    ports:
      - 9094:9090
    command:
      - --config.file=/workspace/.devcontainer/prometheus.yml
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../:/workspace:cached

  grafana:
    image: grafana/grafana:latest
    container_name: jaus-grafana
    networks:
      - jaus_network
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: jaus-tempo
    networks:
      - jaus_network
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - 3001:3001
    command:
      - --config.file=/workspace/.devcontainer/tempo.yml
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../:/workspace:cached

volumes:
  grafana_storage: {}

networks:
  jaus_network:
    external: false
