services:
  postgres:
    container_name: jaus-postgres
    #image: postgres:15-alpine
    image: quay.io/debezium/postgres:18 # https://github.com/debezium/container-images/tree/main/postgres/15 = standard postgres + https://github.com/debezium/postgres-decoderbufs
    networks:
      - jaus_network
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/
      - ./postgres_init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: jaus-kafka
    image: quay.io/debezium/kafka:latest
    networks:
      - jaus_network
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT,CONTROLLER_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER_HOST://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://localhost:9092,CONTROLLER_HOST://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - JMXHOST=kafka
      - JMXPORT=9997

  kafka-connect:
    container_name: jaus-kafka-connect
    image: quay.io/debezium/connect:latest
    networks:
      - jaus_network
    ports:
      - 8083:8083
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=jaus_connect_configs
      - OFFSET_STORAGE_TOPIC=jaus_connect_offsets
      - STATUS_STORAGE_TOPIC=jaus_connect_statuses
      - ENABLE_JOLOKIA=true

  schema-registry:
    container_name: jaus-schema-registry
    image: ghcr.io/aiven-open/karapace:latest
    networks:
      - jaus_network
    ports:
      - 18081:8081
      - 18082:8082
    environment:
      - KARAPACE_BOOTSTRAP_URI=kafka:29092
      - KARAPACE_ADVERTISED_PROTOCOL=http
      - KARAPACE_ADVERTISED_HOSTNAME=localhost
      - KARAPACE_ADVERTISED_PORT=18081
      - KARAPACE_HOST=schema-registry
      - KARAPACE_PORT=8081
    entrypoint:
      - python3
      - -m
      - karapace
    depends_on:
      kafka:
        condition: service_started

networks:
  jaus_network:
    external: false
